project 'd_player.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'd_player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for d_player
  
  pod 'XLPagerTabStrip','8.1.1'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'ARNTransitionAnimator'
end
